# Generated by Django 5.2.6 on 2025-10-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img_tiendas/')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='app_tienda.tienda')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
